package com.example.AirlineTicketAPI.model

import java.util.Date

// Ticket Model
// Getters and Setters are automatically generated by Kotlin, so they are not written for preventing code redundancy.
// For constructor, writing data in class parameters in enough, constructor will be generated by Kotlin.
// Equals, hashcode, toString methods are also generated because this is a data class.
data class Ticket(
    var passenger: String,
    var date: Date,
    var from: String,
    var to: String,
    var passengerCount: Int
)