package com.example.AirlineTicketAPI.model

import jakarta.persistence.Column
import jakarta.persistence.Entity
import jakarta.persistence.GeneratedValue
import jakarta.persistence.GenerationType
import jakarta.persistence.Id

// Ticket Model: Data Layer (Models, Serialization)
// Getters and Setters are automatically generated by Kotlin, so they are not written for preventing code redundancy.
// For constructor, writing data in class parameters in enough, constructor will be generated by Kotlin.
// Equals, hashcode, toString methods are also generated because this is a data class.
@Entity
class Ticket {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    var id: Int = 0

    @Column
    var date: String =""

    @Column
    var from: String = ""

    @Column
    var to: String = ""

    @Column
    var seats: Int = 0

    @Column
    var price: Double = 0.0
}